### ISSUE TITLE
instable service

### ISSUE THREAD

**Issue by camargocr** [infosimples/deathbycaptcha#10]
I tried some searches, but frequently I obtained an error:
puts client.get_user.inspect
I, [2013-09-22T23:40:29.634743 #5840]  INFO -- : SEND: user {:username=>"user", :password=>"pwd"}
DeathByCaptcha::Errors::CallError: HTTP call failed (DEATHBYCAPTCHA API ERROR)
	from /usr/local/lib/ruby/gems/2.0.0/gems/deathbycaptcha-4.1.4/lib/deathbycaptcha/http_client.rb:78:in `rescue in call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/deathbycaptcha-4.1.4/lib/deathbycaptcha/http_client.rb:61:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/deathbycaptcha-4.1.4/lib/deathbycaptcha/http_client.rb:13:in `get_user'
	from (irb):6
	from /usr/local/bin/irb:12:in `<main>'

Sometimes, it works!
What is happening?

**Comment by barbolo** [comment]
@camargocr if you find any error in the future, please communicate us.
