### ISSUE TITLE
Error when captcha URL cannot be loaded

### ISSUE THREAD

**Issue by manuelmeurer** [infosimples/deathbycaptcha#14]
When the URL that is passed to `#decode` cannot be reached for whatever reason, a `RestClient` error is raised: http://screencast.com/t/i4XfjrGHU
How about rescuing that error and wrapping it in `DeathByCaptcha::Errors::CaptchEmpty`?

**Comment by barbolo** [comment]
Hi, @manuelmeurer.

Version 5.0.0 fixes this. Now we have two methods: decode and decode!. If you use decode! with an invalid URL, the exception DeathByCaptcha::InvalidCaptcha will be raised.

When upgrading to the new version, review your code. Version 4.x is incompatible with 5.x.
