### ISSUE TITLE
No banner available

### ISSUE THREAD

**Issue by skypeschematics** [infosimples/deathbycaptcha#19]
What if no banner available with Recaptcha? Only banner text and images grid, like this:
https://dl.dropboxusercontent.com/u/14444860/recaptcha_no_banner.png
Is this a question for a DeathbyCaptcha?

**Comment by barbolo** [comment]
Yes, it should work

**Comment by skypeschematics** [comment]
Looks like client.decode! requires banner as an argument.
How code should look like in such case?

**Comment by barbolo** [comment]
I encourage you to use the Coordinates API:

captcha = client.decode!(type: 2, path: 'path/to/file.jpg') # file.jpg is the screenshot of reCAPTCHA challenge
