### ISSUE TITLE
.status() generates "Invalid API response" error

### ISSUE THREAD

**Issue by JHFirestarter** [infosimples/deathbycaptcha#20]
Rails 4.2.4, Ruby 2.3.0, DBC 5.0.3, able to login to deathbycaptcha.com (i.e. credentials are fine). I'm able to connect to a client `client = DeathByCaptcha.new(ENV["DBCAPTCHA_LOGIN"], ENV["DBCAPTCHA_PASSWORD"], :http)` but checking status `status = client.status()` throws that error.

Have been using for some time (thanks!), but I'm now getting the same error on two different machines. DBC support does not report any issues with my account.

Full error:

    DeathByCaptcha::APIResponseError: Invalid API response: <htmL>
    <body>
    <p>Unable to complete request. Check your account credentials, balance, and ensure you're using the API correctly.<br/>
    If you're receiving this message on our API, please check in our website for Updates notices.<br/>
    If this problem persists, please contact support at help@deathbycaptcha.eu.<p>

    <p>We appreciate your patience and understanding!<p>
    </body>
    </html>

    /Users/user_name/.rvm/gems/ruby-2.3.0/gems/deathbycaptcha-5.0.3/lib/deathbycaptcha/client/http.rb:120:in `perform'
    /Users/user_name/.rvm/gems/ruby-2.3.0/gems/deathbycaptcha-5.0.3/lib/deathbycaptcha/client/http.rb:45:in `status'

**Comment by barbolo** [comment]
Hi, Jim.

Your IP is probably blocked. I recommend you to send an email to help@deathbycaptcha.com with your IP address and asking them to unblock it.

Can you try to run your script from another network/IP?

**Comment by JHFirestarter** [comment]
Ah, will check and close for now. Thanks, Rafael

**Comment by JHFirestarter** [comment]
Seems like it is the IP address. Thanks, Rafael. Now, to fix the "Broken Pipe" error that appears when I use .decode!() further down the script....

**Comment by JHFirestarter** [comment]
@barbolo hah, it's actually the _screenshot_ image size that is the issue. It cannot be over 100 KB. I had upgraded to a retina display and needed to use imagemagick/rmagick to crop images to knock the size down <100 KB before submitting a `decode`. I did not think of that until the IP address was cleared and my older laptop worked fine.
