### ISSUE TITLE
Any plan to support recaptcha type 4?

### ISSUE THREAD

**Issue by hartator** [infosimples/deathbycaptcha#24]
I wonder if there is any plan to support the new format of Google recaptcha (type 4 on DeathByCaptcha website)? 

More info: http://www.deathbycaptcha.com/user/api/newtokenrecaptcha

I can dig into if you want.

**Comment by rafaelivan** [comment]
Thanks, @staszek-arsdata for your PR adding support for type 4.
We'll release version 5.1.0 soon.
