### ISSUE TITLE
The captcha is empty or invalid for type=4

### ISSUE THREAD

**Issue by dvaks** [infosimples/deathbycaptcha#26]
captcha = client.decode!(type: 4, token_params: {
      googlekey: "6LdFNUwUAAAAAKsySNY-VieGpFDe572mZj4wBDLC",
      pageurl: "https://resilienceacademy.com/free_month",
  })

DeathByCaptcha::InvalidCaptcha:
       The captcha is empty or invalid

**Comment by adrianodennanni** [comment]
This site has the Invisible ReCaptcha v2, not a regular ReCaptcha v2.

**Comment by dvaks** [comment]
any way to be able use library in my situation?

**Comment by barbolo** [comment]
Can you use https://github.com/infosimples/two_captcha?

We are not fully testing/supporting reCAPTCHA V2 with DBC client yet.

**Comment by weshatheleopard** [comment]
Running into the same problem as the original poster. Is it the issue with DBC or this gem?

**Comment by RishiHQ** [comment]
Hello, having this issue in May 2020.

To confirm, the issue is the site has the Invisible ReCaptcha v2, not a regular ReCaptcha v2. 

And at least of 2019, the gem did not support ReCaptcha v2? How about now?

Thanks in advance, everyone.

**Comment by rafaelivan** [comment]
We recommend migrating to this: https://github.com/infosimples/two_captcha

**Comment by RishiHQ** [comment]
Thanks, ended up migrating, and works great!
